import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans} from "next/font/google";
import {Toaster} from "@/app/_components/ui/sonner";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} h-screen font-sans antialiased`}
      >
        {children}
      <Toaster />
      </body>
    </html>
  );
}
